### ISSUE TITLE
Đăng nhập

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#1]
-Giao diện : Hiển thị màn hình đăng nhập gồm 1 cái form có :tiêu đề (đăng nhập) , ô nhập tài khoản , ô nhập mật khẩu . Dưới cùng form là nút đăng nhập.
-Xử lý : Người dùng tiến hành nhập thông tin vào ô tài khoản mất khẩu đã được cấp.Nếu đúng  màn hình sẽ  chuyển sang giao diện của người dùng. Nếu sai , màn hình sẽ hiện thị thông báo lỗi sai tài khoản hoặc mật khẩu
-Lưu trữ : Thông tin tài khoản , mật khẩu đã được nhập trước đó , sẽ được lưu trữ vào cơ sở dữ liệu

**Comment by Sonhoang2001** [comment]
Đã xong

**Comment by yangnguyenthuy** [comment]
đã hoàn thành thay đổi
