### ISSUE TITLE
Xem danh sách quyền

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#10]
"-Giao diện : sau khi nhấn vào xem danh sách quyền ở tabmenu , bên trái tabmenu sẽ hiển thị 1 table chứa các trường như : tên quyền , mã quyền , chức vụ . Trên table xem quyền , sẽ có 1 label hiển thị tên Xem danh sách quyền .  Trong table ngoài các trường đã có , sẽ có thêm các chức năng như chỉnh sửa , xóa , và thêm quyền tương ứng với các button mà ta đã tạo trong table.
-Xử lý : sau khi người dùng đăng nhập thành công , ấn vào xem danh sách quyền bên trong thanh tab menu  , sau đó hệ thống sẽ chuyển sang giao diện xem danh sách quyền . 
-Lưu trữ: không hỗ trợ lưu trữ"

**Comment by quocky2211** [comment]
Đã nhận.
