### ISSUE TITLE
Xóa phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#13]
-Giao diện : ở giao diện danh sách phòng , sẽ hiển thị 1 table với các trường như : số phòng , loại phòng , tiện ích , số người tối đa , giá phòng tình trạng phòng , chỉnh sửa , xóa . Ở trường xóa , sẽ có 1 button xóa tương ứng với mỗi phòng. 
-Xử lý : người dùng thao tác nhấn button xóa , hệ thống sẽ hiển thị 1 dialog với label xóa phòng , nội dung bạn có chắc chắn muốn xóa phòng . Theo đó là 2 button ,  1 bên trái là xóa bỏ , 1 bên phải là hủy . Tùy theo như cầu của người dùng . Nếu nhấn vào xóa bỏ  , hệ thống sẽ hiển thị thông báo xóa thành công và load lại màn hình chức năng xem danh sách phòng . 
-Lưu trữ : sau khi xóa thành công , dữ liệu sẽ được cập nhật lại vào hệ thống.

**Comment by Sonhoang2001** [comment]
Đang tiến hành

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
