### ISSUE TITLE
Xóa dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#14]
-Giao diện : ở giao diện danh sách dịch vụ  , sẽ hiển thị 1 table với các trường như :stt , mã dịch vụ , loại  , tên , giá , mô tả , chỉnh sửa , xóa . Ở trường xóa , sẽ có 1 button xóa tương ứng với dịch vụ.
-Xử lý : người dùng thao tác nhấn button xóa , hệ thống sẽ hiển thị 1 dialog với label xóa dịch vụ , nội dung bạn có chắc chắn muốn xóa phòng . Theo đó là 2 button ,  1 bên trái là xóa bỏ , 1 bên phải là hủy . Tùy theo như cầu của người dùng . Nếu nhấn vào xóa bỏ  , hệ thống sẽ hiển thị thông báo xóa thành công và load lại màn hình chức năng xem danh sách dịch vụ. 
-Lưu trữ : sau khi xóa thành công , dữ liệu sẽ được cập nhật lại vào hệ thống.

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
