### ISSUE TITLE
Sửa phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#15]
-Giao diện : giao diện là 1 form nhập với các trường như : số phòng , loại phòng , tên phòng , tiện ích , số người tối đa , diện tích , giá ,  mô tả , hình ảnh . Theo đó , dưới form nhập liệu là 1 button chỉnh sửa  .
-Xử lý : Khi nhận hoặc có yêu cầu chỉnh sửa phòng , sau khi đăng nhập thành công , người dùng click vào chỉnh sửa phòng . sau khi nhập liệu thông tin đầy đủ các trường , người dùng ấn button thêm phòng để hệ thống xác nhận và thông báo thành công sau khi thêm phòng , trường hợp bỏ trống hoặc nhập thiếu trường , hệ thống sẽ báo lỗi và yêu cầu nhập lại đầy đủ các thông tin cần thiết . 
-Lưu trữ : sau khi chỉnh sửa thành công hệ thống sẽ cập nhật lại dữ liệu.

**Comment by nhn010195** [comment]
Nhận nha

**Comment by nhn010195** [comment]
Hoàn thành
