### ISSUE TITLE
Sửa dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#16]
-Giao diện : giao diện là dạng form chứa các trường :mã dịch vụ , loại dịch vụ , tên dịch vụ , giá  , mô tả . Dưới form là 1 button lưu chỉnh sửa . 
-Xử lý : Khi người dùng click vào button chỉnh sửa , hệ thống sẽ chuyển sang giao diện chức năng chỉnh sửa . Chỉ khi người dùng nhập đây đủ thông tin và click button lưu chỉnh sửa , hệ thống sẽ hiển thị thông báo lưu thành công. Trường hợp nhập thiếu hoặc bỏ trống , hệ thống sẽ báo lỗi và yêu cầu nhập lại . Trường hợp hủy thao tác  , hệ thống sẽ quay lại màn hình danh sách dịch vụ. 
-Lưu trữ : sau khi xóa thành công , dữ liệu sẽ được cập nhật lại vào hệ thống.

**Comment by nhn010195** [comment]
Nhận nha

**Comment by nhn010195** [comment]
Done

**Comment by nhn010195** [comment]
Hoàn thành
