### ISSUE TITLE
Xem danh sách phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#17]
-Giao diện : là 1 table với các trường như :số phòng , loại phòng , tiện ích , số người , giá , tình trạng phòng , chỉnh sửa , xóa .  Trên table là 1 label với tên xem danh sách phòng . bên phải label là 1 thanh  search. Ở trường chỉnh sửa và xóa sẽ có các button với chức năng tương ứng. Dưới cùng table là 1 button tạo phòng.
-Xử lý : khi người dùng có nhu cầu xem danh sách phòng , người dùng chỉ cần click vào chức năng xem danh sách phòng ở thanh tabmenu , hệ thống sẽ chuyển sang giao diện xem danh sách phòng. 
-Lưu trữ :  Không hỗ trợ lưu trữ

**Comment by MinhMan1901** [comment]
Đã nhận, đang triển khai.

**Comment by MinhMan1901** [comment]
Đã nhận.
