### ISSUE TITLE
Xem danh sách dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#18]
-Giao diện : ở giao diện danh sách dịch vụ  , sẽ hiển thị 1 table với các trường như :stt , mã dịch vụ , loại  , tên , giá , mô tả , chỉnh sửa , xóa . Ở trường xóa , sẽ có 1 button xóa tương ứng với dịch vụ. Tương tự button chỉnh sửa cũng như thế . Ngoài ra bên phải label còn có 1 thánh search . Dưới table là 1 form nhập liệu để thêm dịch vụ.
-Xử lý : khi người dùng có nhu cầu xem danh sách dịch vụ , người dùng chỉ cần click vào chức năng xem danh sách dịch vụ ở thanh tabmenu , hệ thống sẽ chuyển sang giao diện xem danh sách phòng. 
-Lưu trữ :  Không hỗ trợ lưu trữ

**Comment by MinhMan1901** [comment]
Đã nhận, đang triển khai.

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by MinhMan1901** [comment]
Đã hoàn thành
