### ISSUE TITLE
Xem chi tiết phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#19]
-Giao diện : giao diện là 1 form nhập với các trường như : số phòng , loại phòng , tên phòng , tiện ích , số người tối đa , diện tích , giá ,  mô tả , hình ảnh . Theo đó , dưới form nhập liệu là 1 button chỉnh sửa .
-Xử lý : Khi có nhu cầu xem chi tiết phòng , người dùng chỉ cần click vào mục xem chi tiết phòng được hiển thị ở table chứa các trường như đã nêu ở mục Danh sách phòng. 
-Lưu trữ : Không hỗ trợ lưu trữ.

**Comment by quocky2211** [comment]
Đã nhận.

**Comment by Sonhoang2001** [comment]
Đã nhận, đang tiến hành

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
