### ISSUE TITLE
Xem chi tiết dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#20]
-Giao diện : sẻ hiển thị 1 table chứa các trường như : mã dịch vụ , loại dịch vụ , tên dịch vụ , giá , mô tả , xem chi tiết , chỉnh sửa xóa . Khi click vào xem chi tiết sẽ hiển thị thông tin theo dạng biểu mẫu là 1 form có các thông tin của dịch vụ như :mã dịch vụ , loại dịch vụ , tên dịch vụ , giá , mô tả .
-Xử lý : sau khi người dùng đăng nhập thành công , màn hình sẽ chuyển sang giao diện admin  , với thanh tabmenu bên trái sẽ hiển thị các chức năng  bao gồm chức năng dịch vụ . click vào chức năng dịch vụ sẽ hiển thị chức năng xem chi tiết dịch vụ .
-Lưu trữ: không hỗ trợ lưu trữ.

**Comment by MinhMan1901** [comment]
Đã nhận

**Comment by MinhMan1901** [comment]
Đã hoàn thành
