### ISSUE TITLE
Hủy dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#29]
"-Giao diện : Gồm 1 trong có form hiện các thông tin dịch vụ đã đặt với các thông tin như mã dịch vụ, loại dịch vụ,tên dịch vụ, giá dịch vụ và mô tả, phía bên dưới sẽ có 1 button xóa dịch vụ
-Xử lý : Khi khách hàng có nhu cầu hủy dịch vụ đã đặt, nhấn button hủy dịch vụ để hủy dịch vụ đó
-Lưu trữ: Dữ liệu sẽ được cập nhật sau khi hủy dịch vụ thành công"

**Comment by Sonhoang2001** [comment]
Đã nhận

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
