### ISSUE TITLE
Xem chi tiết đặt phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#33]
"-Giao diện : Gồm 1 trang có 2 phần: phần trên và ph gồm bên trái là thông tin phòng gồm hình ảnh phòng, phần bên phải là các thông tin về diện tích phòng, số lượng người ở, loại giường và các tiện ích khác trong phòng. Bên dưới là phần điền thông tin đặt phòng, bao gồm lable chi tiết đặt phòng, bên dưới label sẽ là form điền thông tin gồm mã số phòng, loại phòng, tên, email, số điện thoại, ngày checkin và checkout. Phía dưới sẽ gồm một button đặt phòng.
-Xử lý : Khi có nhu cầu xem chi tiết phòng , người dùng chỉ cần click vào mục xem chi tiết phòng được hiển thị ở trang.
-Lưu trữ:: không thực hiện lưu trữ dữ liệu"

**Comment by quocky2211** [comment]
Đã nhận.

**Comment by quocky2211** [comment]
Đã hoàn thành
