### ISSUE TITLE
Thêm hóa đơn

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#35]
-Giao diện : Gồm 1 trang có 1 phần gồm label tạo hóa đơn. bên dưới sẽ là phần form điền thông tin như tên khách hàng, số điện thoại, ngày check in, ngày checkout, số phòng, loại phòng, giá phòng, và các chi phí phát sinh .bên dưới form sẽ có button tạo hóa đơn.
-Xử lý : khi admin muốn tạo 1 hóa đơn, điền các thông tin cần thiết và tạo hóa đơn, hóa đơn sẽ được xuất ra thành phiếu chi tiết hóa đơn. 
-Lưu trữ: cho phép lưu trữ

**Comment by quocky2211** [comment]
Đã nhận.

**Comment by quocky2211** [comment]
Đã hoàn thành
