### ISSUE TITLE
Xem tình trạng phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#37]
-Giao diện : Gồm 1 trang có table gồm cách thông tin như số phòng, loại phòng, tiện ích phòng, giá phòng, tình trạng phòng, số người tối đa, và các button chỉnh sửa, xóa,phía dưới cùng sẽ button xem chi tiết phòng.
-Xử lý : Khi admin muốn xem chi tiết phòng đã được cho thuê hoặc còn trống, khi nhấn vào sẽ hiển thị tình trạng phòng.
-Lưu trữ: không lưu trữ dữ liệu

**Comment by quocky2211** [comment]
Đã nhận.

**Comment by quocky2211** [comment]
Đã hoàn thành
