### ISSUE TITLE
Cập nhật tình trạng phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#38]
-Giao diện : Gồm 1 trang có form cập nhật thông tin tình trạng chi tiết phòng, bên trong form sẽ có các mục như: số phòng, loại phòng, tên phòng, tiện ích phòng, số người ở tối đa, diện tích, giá phòng, loại giường, mô tả chi tiết phòng và hình ảnh phòng. bên dưới sẽ có button lưu chỉnh sửa.
-Xử lý : Khi admin muốn cập nhật chi tiết phòng, điền cách thông tin cần cập nhật và bấm lưu chỉnh sửa, các thông tin sẽ được thay đổi và cập nhật
-Lưu trữ: cho phép lưu trữ

**Comment by MinhMan1901** [comment]
Đã nhận, đang triển khai.

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by yangnguyenthuy** [comment]
đã hoàn thành
