### ISSUE TITLE
Cập nhật tình trạng dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#39]
-Giao diện : Gồm 1 trang có form cập nhật thông tin tình trạng dịch vụ, bên trong form sẽ có các mục như: mã dịch vụ, loại dịch vụ, tên dịch vụ, giá dịch vụ, mô tả chi tiết dịch vụ tình trạng dịch vụ và bên dưới sẽ có button lưu chỉnh sửa
-Xử lý : Khi admin muốn cập nhật tình trạng dịch vụ,điền cách thông tin cần cập nhật và bấm lưu chỉnh sửa, các thông tin sẽ được thay đổi và cập nhật
-Lưu trữ: cho phép lưu trữ

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by quocky2211** [comment]
Đã nhận

**Comment by quocky2211** [comment]
Đã hoàn thành
