### ISSUE TITLE
Xem tình trạng dịch vụ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#40]
-Giao diện : Gồm 1 table có các thông tin như mã dịch vụ, loại dịch vụ, giá dịch vụ và tình trang dịch vụ, phía dưới sẽ có button xem chi tiết dịch vụ
-Xử lý : khi admin cần xem chi tiết dịch vụ, nhấn vào button sẽ hiện ra tất cả các thông tin dịch vụ và tình trạng dịch vụ
-Lưu trữ: Cho phép lưu trữ dữ liệu

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by nhn010195** [comment]
Done
