### ISSUE TITLE
Xem danh sách hóa đơn

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#44]
-Giao diện : Gồm 1 trang có 1 phần gồm label xem chi tiết hóa đơn. bên dưới sẽ là phần hiển thị thông tin như tên khách hàng, số điện thoại, ngày check in, ngày checkout, số phòng, loại phòng, giá phòng, và các chi phí phát sinh.
-Xử lý : khi admin muốn xem chi tiết hóa đơn, chọn mã hóa đơn và xem chi tiết
-Lưu trữ: cho phép lưu trữ

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
