### ISSUE TITLE
tìm kiếm

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#46]
-Giao diện : ở màn hình chức năng của admin sau khi đăng nhập , bên tay trái sẽ là tab menu sổ dọc xuống , chứa các tiêu đề chức năng trong đó , bên phải tab menu chính giữa màn hình , bên trên cùng là thanh tìm kiếm .
-Xử lý : sau khi đăng nhập thành công , người dùng thao tác với hệ thống , để nhập dữ liệu vào thanh tìm kiếm sau đó thực hiện tìm kiếm , lúc này hệ thống sẽ trả thông tin tìm kiếm về màn hình chức năng thông qua thông tin đã được lưu trữ trước đó trên hệ thống.
-Lưu trữ : lưu lại các thông tin đã tìm kiếm

**Comment by Sonhoang2001** [comment]
Đã nhận

**Comment by Sonhoang2001** [comment]
Đã hoàn thành
