### ISSUE TITLE
Đánh dấu thanh toán

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#49]
-Giao diện : ở màn hình chức năng thanh toán , trong form thanh toán hiển thị các thông tin liên quan đến thanh toán , bao gồm mã hóa đơn , ngày nhập , ngày xuất , trạng thái , chỉnh sửa , thông tin hóa đơn . Tương ứng với mỗi tiêu đề là 1 cột trong form.
-Xử lý : Khi người dùng đăng nhập thành công , màn hình sẽ chuyển sang màn hình chức năng của admin , người dùng thao tác với chức năng hóa đơn , thanh toán để kiểm tra đánh dấu thanh toán hay chưa.
-Lưu trữ : không hỗ trợ luu trữ

**Comment by nhn010195** [comment]
Done
