### ISSUE TITLE
Xem chi tiết tài khoản

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#6]
"-Giao diện : Ở giao diện trang admin . Ở góc phải màn hình hiển thị 1 icon khi click vào bao gồm . Profile , setting , activity log , logout
-Xử lý : sau khi đăng nhập thành công , màn hình sẽ chuyển sang trang giao diện admin , người dùng thực hiện nhấn vào icon và xem thông tin tài khoản
-Lưu trữ: không lưu trữ"

**Comment by quocky2211** [comment]
-Giao diện : Ở giao diện trang admin . Ở góc phải màn hình hiển thị 1 icon khi click vào bao gồm . Profile , setting , activity log , logout
-Xử lý : sau khi đăng nhập thành công , màn hình sẽ chuyển sang trang giao diện admin , người dùng thực hiện nhấn vào icon và xem thông tin tài khoản
-Lưu trữ: không lưu trữ

**Comment by MinhMan1901** [comment]
Đã nhận, đang triển khai.

**Comment by MinhMan1901** [comment]
Đã nhận.

**Comment by MinhMan1901** [comment]
Đã hoàn thành
