### ISSUE TITLE
Vô hiệu hóa tài khoản

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#7]
- Giao diện: Thêm 1 nút xóa ở trang danh sách tài khoản.
- Xử lý: Sau khi ấn vào nút xóa thì sẽ hiển thị alert xác nhận xóa sau đó thực hiện truy vấn Delete trong database.
- Lưu trữ: lưu trữ dữ liệu sau khi xóa.

**Comment by nhn010195** [comment]
Đang xử lý

**Comment by nhn010195** [comment]
Lam chung vs task Trang chu roi... check giup voi

**Comment by nhn010195** [comment]
Done
