### ISSUE TITLE
Trang Chủ

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#8]
Giao diện:  Bên trái là logo cùng với danh sách các mục, trên cùng của trang là thanh chưa hồ sơ nhân vật nằm bên tay phải, bên dưới là hình ảnh giới thiệu về khách sạn.
Xử lý: Thực hiện lưu tên người dùng đang login, lấy tên người dùng từ dữ liệu đã đăng nhập 
Lưu trữ: không thực hiện lưu trữ dữ liệu

**Comment by nhn010195** [comment]
Đã nhận

**Comment by nhn010195** [comment]
Check giup voi

**Comment by nhn010195** [comment]
Done
