### ISSUE TITLE
Thêm quyền

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#9]
-Giao diện : Ở màn hình giao diện admin , bên tay trái sẽ hiển thị 1 cái tab menu hiển thị các chức năng của hệ thống  , bao gồm chức năng thêm quyền , với giao diện là form bao gồm mã quyền , tên quyền , chỉnh sửa và xóa quyền
-Xử lý : sau khi đăng nhập thành công , người dùng sẽ thao tác với hệ thống , để thực hiện chọn chức năng thêm quyền
-Lưu trữ: dữ liệu sẽ được cập nhật vào sau khi thêm

**Comment by quocky2211** [comment]
Lỗi giao diện . Cần giúp.

**Comment by yangnguyenthuy** [comment]
Tui giúp cho
