### ISSUE TITLE
Sửa loại phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#93]
Giao diện : 
Hiển thị với tiêu đề Sửa loại phòng
Dưới tiêu đề là 1 form nhập liệu với các trường như : Tên loại phòng , Gía loại phòng , Hình , Mô tả
+Mỗi trường sẽ có 1 ô input để nhập 
+Trường Hình : ô input ở đây có type ="file" để chọn các thư mục hình ảnh từ máy 

-Xử lý : 
+TH1 : Người dùng nhập đầy đủ các thông tin vào các trường , sau đó nhấn button Sửa  , web sẽ hiển thị 1 alert thông báo thêm thành công , sau đó load loại trang Danh sách loại phòng . 
+TH2 : Bỏ trống 1 trong các trường , sẽ hiển thị báo và bắt nhập lại . 

-Lưu trữ: Dữ liệu sau khi sửa thành công sẽ được cập nhật về bảng Loại phòng

**Comment by quocky2211** [comment]
Đã nhận

**Comment by quocky2211** [comment]
Đã hoàn thành
