### ISSUE TITLE
Xem chi tiết loại phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#94]
Giao diện : 
Hiển thị 1 thẻ div với tiêu đề là Chi tiết loại phòng : trong thẻ div này chứa 2 thẻ div nhỏ gồm , 1 thẻ chứa hình ảnh được đặt bên phải , và 1 thẻ hiển thị thông tin của loại phòng . 2 thẻ này được đặt dưới tiêu đề , và nằm trong cũng 1 thẻ div lớn hơn nó 
-Thẻ div Hiển thị hình ảnh , được hiển thị bên trái 
-Thẻ div hiển thị thông tin loại phòng , được đặt bên phải  , trong thẻ hiển thị:
   +Header là Tiêu đề : Tên loại phòng (Phòng Standard , Vip , Suit ......)
   +Dưới tiêu đề là body hiển thị các trường như : Mã loại phòng , Gía loại phòng , Mô tảloại phòng.
   +Dưới body là 1 button Sửa thông tin 
-Xử lý : khi người click vào xem chi tiết loại phòng bất kì thì hệ thống sẽ đưa đến trang xem chi tiết loại phòng cùng với id là Tên loại phòng đó, sau đó hệ thống sẽ truy vấn select data ở bảng Loại phòng  sau đó hiển thị dữ liệu sẽ được trả về lên web theo dạng form  ,  bao gồm giá trị của các trường như :  Tên dịch vụ, Mã dịch vụ  , Gía , Mô tả .

-Lưu trữ: không hỗ trợ lưu trữ

**Comment by MinhMan1901** [comment]
đã nhận, đang tiến hành

**Comment by MinhMan1901** [comment]
Đã hoàn thành
