### ISSUE TITLE
Thêm loại phòng

### ISSUE THREAD

**Issue by yangnguyenthuy** [yangnguyenthuy/QuanLyKhachSan#95]
Giao diện : 
Hiển thị với tiêu đề Tạo loại phòng
Dưới tiêu đề là 1 form nhập liệu với các trường như : Tên loại phòng , Gía loại phòng , Hình , Mô tả
+Mỗi trường sẽ có 1 ô input để nhập 
+Ở trường Hình , sẽ có 1 ô input với type ="file" để người dùng thao tác với các thư mục ảnh trên máy . 
Dưới form nhập liệu là 1 button : Tạo

-Xử lý : 
+TH1 : Người dùng nhập đầy đủ các thông tin vào các trường , sau đó nhấn button Thêm quyền , web sẽ hiển thị 1 alert thông báo thêm thành công , sau đó load loại trang Danh sách loại phòng.
+TH2 : Bỏ trống 1 trong các trường , sẽ hiển thị báo và bắt nhập lại . 
+TH3 : Tên loại phòng đã tồn tại sẽ không thể tạo trùng được . 

-Lưu trữ: Dữ liệu sau khi tạo thành công sẽ được lưu về bảng Loại phòng

**Comment by nhn010195** [comment]
Đã nhận

**Comment by nhn010195** [comment]
Done
